version: '3.3'

services:
    #service 1: definition of mysql database
    db:
      image: mysql:latest
      container_name: mysql-db  
      environment:
        - MYSQL_ROOT_PASSWORD=admin123
      ports:
        - "3306:3306"
      restart: always

    #service 2: definition of your spring-boot app
    docker-mysql-springboot-example:                        #it is just a name, which will be used only in this file.
      image: sumitdas28/docker-mysql-spring-boot-example:latest               #name of the image after dockerfile executes
      container_name: docker-mysql-spring-boot-app  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8080:8080"                       #docker containter port with your os port
      restart: always

      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/votingappdb?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: admin123